version: "3"

services:
  qdrant:
    container_name: qdrant
    image: "qdrant/qdrant:latest"
    ports:
      - "${QDRANT_PORT}:6333"
      - "${QDRANT_GRPC_PORT}:6334"
    environment:
      API_KEY: ${QDRANT_API_KEY}
    volumes:
      - /tmp/docker/qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
    network_mode: 'host'
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      test: ["CMD", "true"]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build: .
    ports:
      - "5005:5005"
    environment:
      LOGURU_COLORIZE: "true"
      ENV: "docker"
    volumes:
      - /tmp/docker/llama_index/:/tmp/llama_index/
      - /tmp/docker/nltk/:/root/nltk_data/
      - /tmp/docker/ray/:/tmp/ray/
    network_mode: 'host'
    depends_on:
      qdrant:
        condition: service_healthy
